55: Generate Developer Docs
SasView/sasdata pull request #56
Opened 2023-12-06 23:08 UTC by krzywon

As noted by @smk78, the developer documentation was not present in the build. This PR corrects that mistake.

To check the docs are bundling with sasview properly, please check the builds in https://github.com/SasView/sasview/actions/runs/7121411183/

Fixes #55

2023-12-07 12:34 UTC, smk78 commented
Tested https://github.com/SasView/sasview/actions/runs/7121411183/ on W10/x64.

This PR has indeed fixed the broken sasdata API doc build.

However, it has not addressed a couple of things from my review on #53 .

1) When you go to Developer Documentation you see this:
![image](https://github.com/SasView/sasdata/assets/10938679/5943d0a9-1415-4d5d-b724-706d57ab91a0)
which would be fine, if the link to _sasdata overview_ did give an overview in the same way _sasmodels overview_ does. But all it does is link to this:
![image](https://github.com/SasView/sasdata/assets/10938679/d45b7feb-5099-40c2-a094-ba396d7e174b)
which, in turn, links to API docs:
![image](https://github.com/SasView/sasdata/assets/10938679/10fc52ad-d1eb-4c39-8b1a-f773cd688bb9)
etc.
So my question here is what exactly is the role of /doc/dev/sasdata-dev/dev.html? It seems to be redundant? In which case, why not do away with it and change the top level link from _sasdata overview_ to _sasdata API_?

2) The documents /doc/user/data/data/data_import_help.html and /doc/user/data/data/data_export_help.html are still not linked from anywhere (not even from the 'API' docs) and are only accessible through the search box.

2023-12-07 12:35 UTC, smk78 requested changes
Looking good. The API doc build is now fixed, but there are still a couple of oddities. See above.

2023-12-07 14:55 UTC, krzywon commented
@smk78 - I agree with your first point and just pushed a change to remove the unneeded documentation level.

As far as your 2nd point, the `data_import` and `data_export` help files are specific to the sasdata scripting interface. All of the same information is available in the sasdata developer docs. I purposely omitted those two files from the SasView docs, because the information isn't relevant to the users of the GUI-based program.

2023-12-08 10:06 UTC, smk78 approved these changes
Oh, I see. Ok, then this should be good to merge.

2023-12-08 10:20 UTC, butlerpd commented
> As far as your 2nd point, the `data_import` and `data_export` help files are specific to the sasdata scripting interface. All of the same information is available in the sasdata developer docs. I purposely omitted those two files from the SasView docs, because the information isn't relevant to the users of the GUI-based program.

So reading @smk78 comment -- does this mean these files are orphans because they are duplicates? in which case should we delete them? or are you saying those files are linked through the `sasdata` developer docs?  I worry about "same information" available elsewhere as it makes maintenance a nightmare 😄.

2023-12-19 14:36 UTC, merged